### ISSUE TITLE
Paginated Archive Grid in a Page

### ISSUE THREAD

**Issue by gabrielbajada** [JeremyEnglert/JointsWP#109]
Hi Jeremy,

We're trying to use a paginated archive grid in a page template instead of an archive.

We've managed to make pagination work on a page but we want to use your archive grid. We changed the query to the following:

    <?php
                $temp = $wp_query; $wp_query= null;
                $wp_query = $wp_query = new WP_Query(); $wp_query->query('post_type=post' . '&showposts=3' . '&orderby=date' . '&order=DESC' . '&paged='.$paged);
    ?>

We know we need to pass the arguments to $post, what we need to know is how can we apply our query to the rest of your code?

Thanks,

Gabriel

**Comment by JeremyEnglert** [comment]
Hi Gabriel,

This is something I'm hoping to have flushed out for Joints 4.0. Check out this pull request - it may have what you need: https://github.com/JeremyEnglert/JointsWP/pull/104

**Comment by Erehr** [comment]
I think i got it working. Have 3 templates to loop custom post types using all types of archive (normal,grid,accordion) and working pagination on all of them. In my page template i have: 

<?php 
	if ( is_home() || is_front_page() ) {			
		$paged = (get_query_var('page')) ? get_query_var('page') : 1;
	} else {
		$paged = (get_query_var('paged')) ? get_query_var('paged') : 1;
	} 
	$loop = query_posts ( array( 'post_type' => 'post', 'paged' => $paged,) ); 
?>
<?php get_template_part( 'parts/loop', 'archive-grid' ); ?>

so you may want to give it a try. One thing i found using grid is that 'post_per_page' in archive-grid.php must be set to the same value as wordpress settings, otherwise pagination will not display / or next page will be empty.

**Comment by JeremyEnglert** [comment]
@gabrielbajada, sorry for the slow fix. https://github.com/JeremyEnglert/JointsWP/pull/104 should be merged by the end of the week. Just need to test it.

**Comment by gabrielbajada** [comment]
Hi @JeremyEnglert, was this ever implemented? I've got a the latest version of Joints and I'm trying to put together the category.php template with posts in a grid. Pagination isn't working.

Any idea?
