### ISSUE TITLE
Remove directory "bower_components"

### ISSUE THREAD

**Issue by telekommander** [JeremyEnglert/JointsWP#114]
This should be a part of "bower install", not of the repository.
Add a file .bowerrc that points to the directory containing components.

**Comment by JeremyEnglert** [comment]
Agreed, and in a perfect world, that's how this would be setup.

Unfortunately, not everyone who uses the theme also uses Bower - and since the theme directly calls the Bower files, they had to be included in the repo.

However, in JointsWP 4, this is changing. The files will be located in a "vendor" directory. Bower_Components will be automatically cloned into that directory.
