### ISSUE TITLE
Functionality: Admin Color Scheme

### ISSUE THREAD

**Issue by gabrielbajada** [JeremyEnglert/JointsWP#120]
Hey Jeremy,

I'm not sure if this already exists, but is there any way of creating a custom admin color scheme? Maybe even based using the $primary / $secondary colors in the _main.scss file?

Cheers,

Gabriel

**Comment by JeremyEnglert** [comment]
Hi Gabriel,

Hope all is well!

Here is a really good article I found on creating custom admin color schemes: http://www.hongkiat.com/blog/wordpress-admin-color-scheme/

Since you have to create a new style sheet, it should be pretty easy to use $primary and $secondary variables to create the colors you want. However, I can't think of a good way to use $primary and $secondary inside of PHP to create a matching color swatch - that part might have to be done manually.

**Comment by gabrielbajada** [comment]
Cheers.
