### ISSUE TITLE
Minified Foundation JS

### ISSUE THREAD

**Issue by andycochran** [JeremyEnglert/JointsWP#124]
/assets/functions/enqueue-scripts.php
```
wp_enqueue_script( 'foundation-js', get_template_directory_uri() . '/assets/js/foundation.js', array( 'vendor' ), '6.0', true );
```
Is there a reason you enqueue the non-minified JavaScript? 
Could we instead use `'/assets/js/foundation.min.js'`?

**Comment by JeremyEnglert** [comment]
For some reason, the minified file doesn't seem to work correctly (even though it should be an exact copy of the non-minified file). I haven't quite figured out why, so in the meantime, the theme enqueues the non-minified file.

This is one of the items I'm hoping to figure out sooner rather than later.

**Comment by andycochran** [comment]
Ah. Looks like there are several issues in the Foundation repo relating to minified not matching non-minified. This will probably work itself out in an upcoming patch.

**Comment by JeremyEnglert** [comment]
This has been resolved. 

https://github.com/JeremyEnglert/JointsWP/commit/3d1e318c6e081c5813d815167ebdd5272f3a2495
