### ISSUE TITLE
Deprecated gulp plugins?

### ISSUE THREAD

**Issue by dpkonofa** [JeremyEnglert/JointsWP#168]
What's with all the really, really old gulp plugins?  lodash is still on v1 and they're on v4 now?  Is there a reason besides "if it ain't broke don't fix it" that these are outdated?

**Comment by JeremyEnglert** [comment]
@dpkonofa, I'm working on fixes for some of those here: https://github.com/JeremyEnglert/JointsWP/tree/gulp-updates

lodash isn't actually specified by JointsWP. I believe it is included with one of the gulp-plugins JointsWP uses, so that may need to be updated inside of the plugin itself.

Most of the gulp-plugins are set to download the newest versions anytime they are installed: https://github.com/JeremyEnglert/JointsWP/blob/gulp-updates/package.json

**Comment by JeremyEnglert** [comment]
These updates were pushed to the master branch today.
