### ISSUE TITLE
[Feedback Wanted] Next 'Big' Update

### ISSUE THREAD

**Issue by JeremyEnglert** [JeremyEnglert/JointsWP#185]
Hey everyone,

So I have some thoughts on the next 'big' updates to JointsWP and wanted to outline them here to gather some feedback.

**Gulp Production Tasks**
- Instead of having minified and non-minfied files, there will be a gulp task that will minify your files when you're ready for production. Think: `gulp styles -production`
- Not sure the best way to approach this. 
- We can add in a plugin like [yargs](https://github.com/yargs/yargs) to create production flags (downside: adds an additional dependacy) or,
- Create separate tasks that includes the additional steps (downside: extra code). 

**NPM Scripts**
- We'll get rid of the Gulp Global dependency by setting up the tasks to run as NPM scripts. This simply keeps users from having to install gulp locally and globally.
- So instead of `gulp styles`, it would be `npm styles`
- Based on '[Build Tools vs npm Scripts: Why Not Both?'](http://engineering.hobsons.com/2015/06/26/build-tools-vs-npm-scripts-why-not-both/)
- This also sets us up to eventually completely shift to using NPM scripts instead of Gulp (in the distant future).

**File Structure**
- Move function files into an /includes/ directory

**Cleaner Gulp File**
- Cleaner by using variables for repeated sourcepaths - this also makes it easier to change those paths

**Better Documentation**
- Inline documentation on files, especially template parts such as the navigation where it is not immediately evident how they function
- Better readme file for github

**Comment by kemie** [comment]
For a newbie not at all familiar with gulp or npm, my only input is:
I work with codekit, and my only request is that it keep on working seamlessy as it does now.

**Comment by JeremyEnglert** [comment]
@kemie - the Codekit config file will stick around. But this will make it even easier to try out Gulp if you decide to give it a shot.

**Comment by JeremyEnglert** [comment]
@mrscharf would love to hear your feedback.

**Comment by mrscharf** [comment]
Being rather new to gulp and npm, I don't have much input there other than it sounds like a good idea sorting the local/global install stuff. That gave me some hiccups when I was getting gulp working the first time.

It might also be good to have some examples of custom media queries added to the scripts file. This was highlighted in issue #159 and was rather tricky to figure out. Mostly because of the ( ) being removed from the syntax and Foundation not pointing that out, and then by where the code had to go.

Moving the scripts and styles enqueues directly into the functions file seems to make some sense too. This would help consolidate file loading operations.

On a new content note, I would think adding more templates/integrations for different parts of Foundation like the clearing lightbox, different menu types or even making different configurations for the top bar and mobile menu might be helpful. The menu types would likely mean the topbar and offcanvas parts would need combined back into a larger piece, which seems to make sense as they're all intimately tied together.

One other thing that might be helpful, if only slightly, would be adding links back to the Foundation docs in the code. So when you're staring at the top bar or whatever, there's a link pointing to the doc right there with it. This would also help ensure folks find the correct docs for the version of Foundation being used, but would also mean updating could be a hassle as the links would need updated.

**Comment by kball** [comment]
@JeremyEnglert with respect to the production/non, another common approach is to use an environment variable.  e.g. `NODE_ENV=production gulp styles`

**Comment by JeremyEnglert** [comment]
@kball I was leaning towards that until I noticed Foundation is using `yargs` - so for the sake of consistency, JointsWP will use a similar setup.

**Comment by Shipwreck** [comment]
Just starting another project with my favorite framework (joints, duh!) and came to poke around and see whats new. How's the update coming along? 

Thanks for everything and keep up the great work.

**Comment by garrett-eclipse** [comment]
Hey @JeremyEnglert, not sure if would go in line with your vision for JointsWP but some Foundation shortcodes would be epic, opened a feature request here;
https://github.com/JeremyEnglert/JointsWP/issues/212
Thanks
