### ISSUE TITLE
Can Foundation 6 files be updated with Bower?

### ISSUE THREAD

**Issue by jfc4** [JeremyEnglert/JointsWP#222]
Using the JointsWP Sass version, Foundation 5 files could be updated using "bower update". Is this still true for Foundation 6 files, or has the update process been changed?

I couldn't tell from the JointsWP docs and saw some conversations on here about removing Bower dependency, so just wanted to find out where you are on this.

**Comment by garrett-eclipse** [comment]
Yes you can do it manually or via bower;
Manual - http://jointswp.com/docs/updating-foundation/
Bower - http://jointswp.com/docs/bower/

**Comment by JeremyEnglert** [comment]
@garrett-eclipse is correct! It is currently possible.

However, in the next version of JointsWP, we will use NPM instead of Bower for managing the dependancy. Foundation "raw" files will never be uploaded to the production site - we'll be treating Foundation more like a development tool opposed to a theme asset.

**Comment by jfc4** [comment]
Thanks for your responses. Glad to know it can be updated now, but will prepare for NPM for the next release of JointsWP.
