### ISSUE TITLE
Orbit - Graceful Load?

### ISSUE THREAD

**Issue by Shipwreck** [JeremyEnglert/JointsWP#226]
Never noticed until I got on a slower connection that Orbit loads the gallery vertically before turning into a carousel. Built two sites recently that have an orbit carousel on the landing page: [stretcheveryday.yoga](http://stretcheveryday.yoga/) and [shantiyoga.ca](http://shantiyoga.ca/)

Found some CSS solutions ([here](http://foundation.zurb.com/forum/posts/3163-display-first-image-while-others-loads---orbit) and [here](https://github.com/zurb/foundation-sites/issues/1707)) but they are older.  Has graceful load not been integrating into vanilla Orbit? I see the [Orbit Demo](https://foundation.zurb.com/sites/docs/orbit.html) hides images until they are loaded. Can't tell if the Joints Orbit demo works as intended with just text content.

Using Foundation 6.1 via JointsWP 4.0

Please advise, Thanks!

**Comment by JeremyEnglert** [comment]
JointsWP doesn't do anything different than Foundation (in regards to Orbit) - and it looks like others are having the same issue who are not using JointsWP. This makes me think it's a Foundation issue.

However, it can probably be fixed by using the following:

    .no-js .orbit-image {
        display: none;
    }

This will hide the images until the JS has fully loaded. Let me know if this works for you.

**Comment by Shipwreck** [comment]
Not quite graceful but it is an improvement. Thanks!
