### ISSUE TITLE
Dropdown links not working on tablets

### ISSUE THREAD

**Issue by giantleif** [JeremyEnglert/JointsWP#277]
We are using the dropdown menu as a the main navigation. On tablets the links are not working.

Tapping a top level link will open the dropdown, but when you click on one of the submenu links, nothing happens.

See for example:

vcc.giantvoices.com

Same issue seen here:

https://github.com/olefredrik/FoundationPress/issues/1072

**Comment by jnorthard** [comment]
@giantleif - Foundation has documented how to enable the parent links here: http://foundation.zurb.com/sites/docs/accordion-menu.html#submenu-toggle

Add `data-submenu-toggle="true"` to your `joints_off_canvas_nav` function.

**Comment by giantleif** [comment]
Sorry, let me clarify, I meant to say that when you click on any of the sub-menu links, nothing happens and then the dropdown menu will not close either.

**Comment by jnorthard** [comment]
@giantleif - Interesting, it looks like you're running version 6.3.1.  I'd recommend [updating](http://jointswp.com/docs/updating-foundation/) locally to see if the fix is in a newer version.  It is functioning properly for me with Chrome dev tools - I don't have a tablet around for additional testing.

**Comment by JeremyEnglert** [comment]
Seems like this may have been a Foundation bug: https://github.com/zurb/foundation-sites/issues/9484
