### ISSUE TITLE
Off canvas issues in older browsers

### ISSUE THREAD

**Issue by johnw6761** [JeremyEnglert/JointsWP#281]
I am having some issues with the off canvas menu in some older browsers (Safari 8 and IE 9).  The off canvas menu is not hiding and is permanently showing, also the menu content seems to be being repeated. I have attached screen shots showing the issue in safari 8.

![macyos_safari_8 0](https://user-images.githubusercontent.com/9976925/30768352-0603790a-9ffe-11e7-8eb2-52f9e9655dc7.jpg)

**Comment by JeremyEnglert** [comment]
Do you have a link I can check out?

I don't think Safari 8 is supported by Foundation 6. https://foundation.zurb.com/sites/docs/compatibility.html

**Comment by johnw6761** [comment]
Hi, thanks for the reply. Link is http://helenkeeble.co.uk . I get the same issue in IE9 too which foundation says it does support?

**Comment by johnw6761** [comment]
Anyone have any ideas on this issue or have experienced anything similar?

**Comment by garrett-eclipse** [comment]
I can't say for sure, but when inspecting on IE9 I noticed the transform CSS is missing most likely IE9 just doesn't render it as it only supports the -ms-transform and not transform. Are you compiling this wil an autoprefixer? You can tell it to auto prefix for IE9 so as to inject the -ms-transform version. Or manually add that. Hopefully that'll fix the always display issue may need the -webkit-transform for the Safari browser you're trying to support.

And as to your duplicate menu, that's a screenshot and not what you actually see right. I've seen that with fixed elements in screenshots for Awesome Screenshot and on Browser stack. It's misleading but happens because the screenshot program takes a shot, scrolls down then takes another shot. When it scrolls down your menu moves so it'll appear multiple times in the screenshot.

*I may be wrong but that's my two cents ;)

**Comment by johnw6761** [comment]
Thanks for your reply @garrett-eclipse . Strangely I have done some tests on sites where I have used joints and the issue only seems to be on the sites where I have used the SASS version. Any ideas?

**Comment by garrett-eclipse** [comment]
Hi @johnw6761 that makes sense, in the autoprefixer it's set to 'last 2 versions' which when run only generates transform and none of the vendor prefixes versions.
If you crack open your gulpfile.js and replace 'last 2 versions' with '> 0%' then rerun gulp it'll autogenerate all the vendor prefixes (just tested this).
Then upload that version of the css and retest. Hoping it resolves your issue.
If so @JeremyEnglert should the autoprefixer be revisited so the browsers it renders for covers all ones mentioned by Foundation (basically to include IE9 support).
Cheers

**Comment by johnw6761** [comment]
@garrett-eclipse THANK YOU SOOOOOOO MUCH! That worked perfectly. I cant believe more people havent reported this issue. I have a lot of clients still on IE9 (unfortunately).

Thanks again!

**Comment by garrett-eclipse** [comment]
Nice, that's awesome @johnw6761.
So sounds like JointsWP will need to revisit the autoprefixer setting in gulpfile.js to support IE9 and any others listed in Foundation's browser support matrix. 
@JeremyEnglert should we spawn another ticket to look at that or is this sufficient to prompt a look at the autoprefixer default?
Thanks

**Comment by JeremyEnglert** [comment]
Nice catch and HUGE thanks @garrett-eclipse.

I'll update the Gulpfile to match the Foundation one. https://github.com/zurb/foundation-zurb-template/blob/ed03998aadfbacbba74a27b45446a6d686b2ed84/config.yml

**Comment by garrett-eclipse** [comment]
Nice, good call @JeremyEnglert thank you

**Comment by JeremyEnglert** [comment]
JointsWP 5 is live now. This has been addressed.

**Comment by garrett-eclipse** [comment]
Thanks @JeremyEnglert
