### ISSUE TITLE
Woocommerce Storefront HTTP Error 500

### ISSUE THREAD

**Issue by NanoSilverDistributors** [JeremyEnglert/JointsWP#291]
Hi There,

I hope some here can help me. I have ZERO coding experience, but (cleverly) tried to change something on the Word Press/Woocommerce site using information I'd found in a Google Search (really smart, I know).

Essentially, I was trying to remove the "Add To Cart" buttons on the Storefront Homepage in the Featured Products section. I found a thread on CloudWays that dealt with a similar problem, and explained where to go to add code, which was in woocommerce.php (found in the plugins folder).

I then found another thread on WordPress.org, where someone suggested a piece of code to include to remove these specific buttons.

So, I went to Plugins>Editor>Woocommerce>Woocommerce.php

Then, after this:
*
 * Returns the main instance of WC to prevent the need to use globals.
 *
 * @since  2.1
 * @return WooCommerce
 */

I added the following:
add_action( ‘woocommerce_after_shop_loop_item’, ‘remove_add_to_cart_buttons’, 1 );

function remove_add_to_cart_buttons() {
if(is_product_category() || is_shop()) {
remove_action( ‘woocommerce_after_shop_loop_item’, ‘woocommerce_template_loop_add_to_cart’ );
}
}

And now I get:
This page isn’t working
dev.nanosd.co.za is currently unable to handle this request.
HTTP ERROR 500

when I try to log in to WordPress or try to view the frontend of the site.

Is there any way that someone could advise me on how to perhaps undo this?

Thanks in advance.
Sam.

**Comment by garrett-eclipse** [comment]
Hi Sam,

In future you'll want to post on WooCommerce here - https://github.com/woocommerce/woocommerce
*Or probably better in WooCommerce's WordPress support forum here - https://wordpress.org/support/plugin/woocommerce

That being said you're running into this issue because you've modified the WooCommerce plugin itself. Instead go into your theme wp-content/themes/storefront(or child name) and find the woocommerce.php file there. If one doesn't exist then instead modify the functions.php to add your code there.

Hope that leads you down the right path.

Cheers

**Comment by JeremyEnglert** [comment]
As @garrett-eclipse noted, this doesn't appear to be JWP specific so I'm going to close this out.

PS - Thanks for answering this @garrett-eclipse!
