### ISSUE TITLE
Node scss files not compiling

### ISSUE THREAD

**Issue by mlangone** [JeremyEnglert/JointsWP#295]
Fresh install npm install, npm watch, 

I believe the node_modules scss files are not being compiled correctly and output to the final .css file.  I can still see them all in dev tools.

![screen shot 2017-11-09 at 6 21 54 pm](https://user-images.githubusercontent.com/4027703/32638156-092322c8-c57b-11e7-8122-a70508c6953c.png)

**Comment by garrett-eclipse** [comment]
Hi @mlangone 
What you're seeing is due to scss source maps, which some people call Magic ;)
It's expected, when you have scss map file then DevTools is able to make the leap from your css to your scss making it easier to troubleshoot.

More info;
https://code.tutsplus.com/tutorials/developing-with-sass-and-chrome-devtools--net-32805
https://robots.thoughtbot.com/sass-source-maps-chrome-magic

**Comment by mlangone** [comment]
Thanks for the direction this makes alot more sense now. Magic!
