### ISSUE TITLE
How to go back to foundation-grid?

### ISSUE THREAD

**Issue by grocc** [JeremyEnglert/JointsWP#327]
Hello,
for some browser support requirements i need to go back and use foundation-grid.
I've changed styles.scss and set
`// Select the grid you would like to use
@include foundation-grid;
// @include foundation-flex-grid;
//@include foundation-xy-grid-classes;`
then in _settings.scss i've set
`$global-flexbox: false; //true;`
Now the theme use the standard class for the [foundation grid](https://foundation.zurb.com/sites/docs/grid.html), but all the .php file in the theme have the standard class for the xy-grid (like grid-x, cell, ...).
Does anybody know if there is a fast way to manage all with the standard class of the basic grid?
Thanks

Giovanni

**Comment by KiwiCreative** [comment]
So I'm not sure I completely understand your question. but it sounds like you are wanting to use the float grid instead of the flex or xy grids. 

You did the first part, commenting out the flex and xy grid classes include statements, and set the global-flex box variable to be false. Now you have to update the usage of these classes in the template files. 

What I would recommend doing is a global find and replace. Swap 'grid-x' with 'row' and 'cell' with 'columns'. Hopefully your code editor or IDE has the capability to do an entire site find and replace. You should be able to replace all instances in one fell swoop.  Using this method will leave some xy-grid stuff in like usage of .grid-container, .grid-padding-x and .grid-margin-x, but those shouldn't affect your site if you commented out the @include foundation-xy-grid-classes. but you could also do a find and replace, just replacing those with an empty string.

**Comment by JeremyEnglert** [comment]
@KiwiCreative is 100% correct. You'll have to do a find/replace, there isn't a way to automagically do this. However, that is something I'll consider for a future update.

**Comment by grocc** [comment]
For sure find and replace is working, and is what i've done exactly when i wrote.
I was thinking for a fork with the right files :)

**Comment by JeremyEnglert** [comment]
In a perfect world, we'll only have one grid in the next version of Foundation - but that also could be wishful thinking!
