### ISSUE TITLE
Pagination problem

### ISSUE THREAD

**Issue by Chowix** [JeremyEnglert/JointsWP#334]
Hi. After update to WooCommerce 3.3.3 (3.2.6 it works properly) appeared problem with products pagination. Once you click on the next products page then appears new page with exactly these same products like on the 1st products page. 
When I switch template to the default woocomerce template this feature works normally but unfortunately not on JointsWP. 
Can you help me please?
Regards,
Dawid

**Comment by garrett-eclipse** [comment]
Hi Chowix, JointsWP by default doesn't have WooCommerce support so that must be built in currently. Check your templates and versions on the customized local templates, if you go into WooCommerce > System Status it'll tell you which templates are out of date. Hopefully this help you;
https://docs.woocommerce.com/document/fix-outdated-templates-woocommerce/

But looking at their changelog it's most likely 3.3.0 or 3.3.1 and their pagination changes that caused you trouble;
https://github.com/woocommerce/woocommerce/blob/master/CHANGELOG.txt

If you're still stuck after updating templates hop over to WooCommerce as their support will be best suited to help you;
*If you're paying customer ask on https://woocommerce.com/
Or use the WP forum;
https://wordpress.org/support/plugin/woocommerce

Good luck, going to close this as it doesn't apply directly to JointsWP.
