### ISSUE TITLE
Large Folder Size to Upload to Wordpress? Normal or What Files are Mandatory?

### ISSUE THREAD

**Issue by jwindeknecht** [JeremyEnglert/JointsWP#336]
My question, I've finished my building and the final size of my theme is about 136 MB. Is this normal and I should just upload the whole folder to Wordpress? Or are there only certain files and folders that I would need to upload? I was curious of best practice and recommendation. Thanks!

P.S. If this is not the proper forum for these types of questions, please let me know and I'll hop on SO.

**Comment by garrett-eclipse** [comment]
Hi @jwindeknecht 

Unless you require the SCSS files for Foundation due to use of WP-SCSS or SCSSPHP then you don't need anything listed in the .gitignore file on the WP install so the main folders which are only used for development are `node_modules` and `bower_components` killing them before upload to your WP install should cut your theme size down drastically.

Hope that helps,
Cheers
P.S. If you have any issues or further questions feel free to reopen this.
