### ISSUE TITLE
Page Navi on custom blog template

### ISSUE THREAD

**Issue by dancrowe** [JeremyEnglert/JointsWP#345]
Hi,

Im trying to use the page navi function on a custom template that im using to show the blog. It is just giving me false reading though. If you look at the url at top is says its on the page you clicked on but really nothing changes. Here is the page in question. 

https://vtsociety.org/newsroom

This is using just the normal wordpress "Post" but its on a custom template I created so its probably not using the default wordpress query to gather all the post into one page. 

I think this was using Joints4 or 5. I know the page navi changed in 6 and thats not what i have. 

Any advice on getting this working?

Thanks
-Dan

**Comment by garrett-eclipse** [comment]
Hi Dan,

Can you share the coding of your custom template?

My assumption is you're using get_posts rather than the standard WP_Query, the normal query looks something like this which you can find in the current JointsWP index.php;
`<?php if (have_posts()) : while (have_posts()) : the_post(); ?>`

If you are using a standard query look at the structure here for differences;
https://github.com/JeremyEnglert/JointsWP/blob/master/index.php

However if you're using get_posts then you'll have to switch to using the WP_Query loop you can find info on that here;
https://codex.wordpress.org/Class_Reference/WP_Query

Otherwise you'll need to rewrite page_navi without $wp_query params.
Current implementation - https://github.com/JeremyEnglert/JointsWP/blob/master/functions/page-navi.php
Docs on paginate_links - https://codex.wordpress.org/Function_Reference/paginate_links

Hope that helps,
Cheers

**Comment by dancrowe** [comment]
Here is the code, looking into the options you have listed now. Thanks for the response. 

`		<div id="inner-content" class="row">
		    <main id="main" class="large-8 medium-8 columns" role="main">
		    <h2 class="event-subtitles"><span>Recent</span> Articles</h2>
		    <?php query_posts('cat=-9');
				if (have_posts()) : while (have_posts()) : the_post(); ?>
					<div class="row blog-content" itemprop="articleBody">
						<div class="small-12 columns">
							<div class="blog-info">
								<a href="<?php the_permalink(); ?>"><h4><span><?php the_field('new_post_title'); ?></span> <?php the_title(); ?></h4></a>
								<p class="blog-meta"><?php the_time('j F, Y') ?> | <?php the_category(', ') ?></p>
								<p><?php the_excerpt(); ?></p>
							</div>
						</div>
					</div>
				<?php endwhile; ?>	
					<?php joints_page_navi(); ?>
				<?php else : ?>						
					<?php get_template_part( 'parts/content', 'missing' ); ?>
				<?php endif; ?>
			<?php wp_reset_query(); ?>																				
		    </main> 
		    <div id="sidebar1" class="sidebar large-4 medium-4 columns" role="complementary">
				<?php if ( is_active_sidebar( 'news-sidebar' ) ) : ?>
					<?php dynamic_sidebar( 'news-sidebar' ); ?>
					<?php dynamic_sidebar( 'global-sidebar' ); ?>
				<?php else : ?>
								
				<div class="alert help">
					<p><?php _e( 'Please activate some Widgets.', 'jointswp' );  ?></p>
				</div>
				<?php endif; ?>
			</div>
		</div> `

**Comment by garrett-eclipse** [comment]
Thanks @dancrowe I see what's going on now. 

You're using query_posts function without paged so the pagination index isn't passed into the paginate_links function found in joints_page_navi.

There's a note on that function;
"Pagination won’t work correctly, unless you set the ‘paged’ query var appropriately: adding the paged parameter"
Reference - https://developer.wordpress.org/reference/functions/query_posts/#pagination

Here's the documentation for adding that;
https://codex.wordpress.org/Pagination#Adding_the_.22Paged.22_Parameter_to_a_Query

Hope that helps,
Cheers

**Comment by dancrowe** [comment]
Perfect, thanks for your help. I was able to get this working.

**Comment by garrett-eclipse** [comment]
Nice, happy to hear
