### ISSUE TITLE
Compiling Scripts

### ISSUE THREAD

**Issue by meiskv** [JeremyEnglert/JointsWP#350]
I thought after I build the scripts no-one could ever look into the code because it was compiled in main.js if im not mistaken. But I found out the in inspect tab under source you can toggle thru the directory of theme/assets/scripts/  " your un compiled scripts ". I was wondering if its really how it works or I am doing it wrong? I don't want for others to inspect on my code or lets say to hide it. Thanks!

**Comment by garrett-eclipse** [comment]
Hi @meiskv 

JointsWP uses the Babel JavaScript compiler (https://babeljs.io/) along with gulp-sourcemaps for compiling code.

The reason you can inspect the uncompiled scripts is because of the sourcemaps, more information about JS sourcemaps here;
https://www.html5rocks.com/en/tutorials/developertools/sourcemaps/

Basically the sourcemaps hold references for the compiled code so that when you inspect from a browser you're able to see the uncompiled source for troubleshooting, etc.

You can remove the sourcemaps process from the script compiling by removing the init and the write actions;
sourcemaps.init - https://github.com/JeremyEnglert/JointsWP/blob/master/gulpfile.js#L92
sourcemaps.write - https://github.com/JeremyEnglert/JointsWP/blob/master/gulpfile.js#L126

Compiling without sourcemaps means users inspecting will only see the compiled version. But they can beutify that code or uncompress to have a readable version again.

You'll never be able to completely hide your code as it's online, but you can look into obfuscating it and there's gulp tools for that which you can use to update your compile process;
https://www.npmjs.com/package/gulp-obfuscate
https://www.npmjs.com/package/gulp-javascript-obfuscator

Play around with that and hopefully it'll help.

I'm going to close this as it's not an issue with JointsWP and I doubt we'd ever bake js obfuscation into the theme.

Cheers
