### ISSUE TITLE
Warning:  count(): Parameter must be an array or an object that implements Countable in wp-includes/post-template.php on line 284

### ISSUE THREAD

**Issue by markjcasey** [JeremyEnglert/JointsWP#377]
Hi
I'm not really sure if this is a JointsWP error but I'm not having much luck tracing the cause of it. It's to do with running Wordpress on php 7.2 (no error on 7.1).

I found this: https://core.trac.wordpress.org/ticket/42814#comment:57

Have you come across this error at all. Appreciate any help.

Thanks

**Comment by garrett-eclipse** [comment]
Hi @markjcasey 

Taking a look at Trac and the code in core triggering your error;
https://github.com/WordPress/WordPress/blob/4.9.8/wp-includes/post-template.php#L284-L285

You're correct in the comment on Trac (https://core.trac.wordpress.org/ticket/42814#comment:57) about it being called outside of the loop. The core ticket there has a null check proposed so hope that's addressed upstream.

As to JointsWP, it doesn't call count directly but does use the_content within its loop templates;
https://github.com/JeremyEnglert/JointsWP/search?utf8=%E2%9C%93&q=the_content&type=

If these are called outside of the loop it would trigger the error, or if you're calling the function directly in the custom code it may trigger it as well.

Another case that often explains the execution of these functions and others like get_header, get_footer and standard template functions that are expected to load after wp-init is due to bots/hackers/probes/etc trying to call PHP files directly within your theme. We get this all of the time when I see an error_log inside the theme folder it's often related to direct hits on theme files.

So first I'd check any custom code calling get_the_content/the_content and make sure they're inside the loop. Then if it seems like it's more those loop files being called directly make sure your site it updated and secure and you should be ok.

Closing as unrelated to JWP. 

All the best
