### ISSUE TITLE
Remove Bower dependencies from repository

### ISSUE THREAD

**Issue by kalenjohnson** [JeremyEnglert/JointsWP#82]
I assume that having `bower_components` checked in to the repository makes it easier for newcomers to get going. However, if the theme basically depends on using Bower, as far as package managers go, the dependencies have no need to be included in the repository.

Also probably don't need this file in the repo either: https://github.com/JeremyEnglert/JointsWP/blob/master/config.codekit

**Comment by JeremyEnglert** [comment]
Great points.

The theme enqueues files from the bower_components folder, but that doesn't mean you are required to use it. You can simply rename that folder anything you want then update a few paths and you're set. 

However, because the theme relies on the files inside of bower_components to function, they are included in the repository. 

I've been on the fence about removing the CodeKit file, but its also pretty beneficial as it eliminates the step of needing to configure CodeKit.

**Comment by JeremyEnglert** [comment]
I'm going to close this for now, let me know if you have any other questions or concerns.
