### ISSUE TITLE
Loop archive grid

### ISSUE THREAD

**Issue by altjon** [JeremyEnglert/JointsWP#90]
Hi,

can you check the page pagination when using Loop Archive Grid to show posts?

I get a Fake pagination, the numbers of the pages at the bottom page navigation don't adjust after changing the settings posts_per_page on:

<?php						
	$paged = (get_query_var('paged')) ? get_query_var('paged') : 1;	
	$args = array (
		'posts_per_page' => 9,
		'paged' => $paged,
	);
	$posts = get_posts( $args );
?>

**Comment by altjon** [comment]
I don't know if I was clear enough on this one:
If I have 12 posts and choose to show 3 posts per page, I get 4 pages in the navigation. That's right!
If I choose to show 6 posts per page I get 4 pages in the navigation again and 2 of them are empty. That's wrong :(

**Comment by DaveG43** [comment]
I dont know if this has anything to do with your issue, but I have been caught out on something like this before with wordpress where the posts per page number is directly related to the Reading settings under wp-admin/options-reading.php. Try changing the "Blog pages show at most" number to see if it makes a difference.

**Comment by altjon** [comment]
You're right, but, if I change to "Blog pages show at most" I still get only 9 posts per page and NO pagination at all, even if there are more than 9 posts ...
Something is missing here, the Loop Archive Grid file should override the wordpress pagination settings. Am I wrong?

**Comment by DaveG43** [comment]
I think your problem is more a misunderstanding of wordpress terms rather than WPJoints itself. 
get_query_var('posts_per_page') = your settings under dashboard - settings- - reading - Blog pages show at most [ ] posts;

To get pagination working right:
'numberposts' => 6, then change your Blog pages show at most to 6
'numberposts' => 9, then change your Blog pages show at most to 9

you could also leave those settings alone and put the script below into your functions.php file. Set the numbers according to your preference and they will control the pagination and posts independently of your read settings.

    function custom_posts_per_page($query) {
    if (is_home()) {    
        $query->set('posts_per_page', 8);
    }
    if (is_search()) {
        $query->set('posts_per_page', -1);
    }
    if (is_archive()) {
        $query->set('posts_per_page', 3);
    } //endif
    } //function
    add_action('pre_get_posts', 'custom_posts_per_page');
    
Hope that helps :)

**Comment by altjon** [comment]
Thanks, got it :)

Case closed ;)

**Comment by JeremyEnglert** [comment]
:+1:  to @DaveG43. I just learned something new too.
